name: Deploy aplication Canban
on: [workflow_dispatch, pull_request, push]
jobs:
  deployment:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Inctall dependencies
        run: yarn
      - name: Test aplication
        run: yarn test:cypress
      - name: build
        run: yarn build
