name: Deploy aplication Canban
on: [workflow_dispatch, pull_request,push]
jobs:
  deployment:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Inctall dependencies
        run: yarn
      - name: Test aplication
        run: yarn test:cypress
      - name: eslint
        run: yarn eslin
      - name: stylelint
        run: yarn stylelint
      # - name: build
      #   run: yarn build
